sudo wget -O splunk-8.2.0-e053ef3c985f-linux-2.6-amd64.deb 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.2.0&product=splunk&filename=splunk-8.2.0-e053ef3c985f-linux-2.6-amd64.deb&wget=true';
sudo dpkg -i splunk-8.2.0-e053ef3c985f-linux-2.6-amd64.deb;
sudo cd /opt/splunk/bin;
sud0 ./splunk start --accept-license;
sudo ./splunk stop;
sudo ./splunk enable boot-start -user splunk;
sudo chown -R splunk:splunk /opt/splunk;
su - splunk;
cd /opt/splunk/bin;
sudo /opt/splunkforwarder/bin/splunk start;
